apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service-deployment
  labels:
    app: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
      - name: shop-service
        image: praspit/sds-shop-service:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: shop-service-service
spec:
  selector:
    app: shop-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000